[project]
name = "benang-merah-perpisahan-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lxml>=5.4.0",
    "pymupdf>=1.26.0",
    "rapidfuzz>=3.13.0",
    "scrapy>=2.13.0",
    "tqdm>=4.67.1",
]
