[project]
name = "benang-merah-perpisahan-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.11.18",
    "beautifulsoup4>=4.13.4",
    "pandas>=2.2.3",
    "psutil>=7.0.0",
    "pypdf2>=3.0.1",
    "python-magic-bin>=0.4.14",
    "scrapling>=0.2.99",
    "tenacity>=9.1.2",
]
